version: '3'
services:
  classifier:
    build: ./app
    volumes:
      - ./app:/app/app
      - ./classifier:/app/classifier
      - ./data:/app/data
      - ./machine_readable:/app/machine_readable
      - ./models:/app/models
      - ./scripts:/app/scripts
    environment:
      - MODULE_NAME=app.main
    ports:
      - 9080:80
